repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive]
  - repo: local
    hooks:
    - id: generate docs
      name: generate docs
      entry: python scripts/generate_docs.py
      language: system
      always_run: true
      pass_filenames: false
  - repo: local
    hooks:
    - id: generate json schemas
      name: generate json schemas
      entry: python scripts/generate_json_specs.py
      language: system
      always_run: true
      pass_filenames: false
  - repo: local
    hooks:
    - id: generate passthrough modules
      name: generate passthrough modules
      entry: python scripts/generate_passthrough_modules.py generate
      language: system
      always_run: true
      pass_filenames: false
  - repo: local
    hooks:
    - id: generate_weights_formats_overview
      name: generate_weights_formats_overview
      entry: python scripts/generate_weights_formats_overview.py generate
      language: system
      always_run: true
      pass_filenames: false
