repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
  - repo: local
    hooks:
    - id: generate docs
      name: generate docs
      entry: python scripts/generate_docs.py
      language: system
      always_run: true
      pass_filenames: false
  - repo: local
    hooks:
    - id: generate json schemas
      name: generate json schemas
      entry: python scripts/generate_json_specs.py
      language: system
      always_run: true
      pass_filenames: false
