version: 0.0.1
language: python
framework:
    pytorch: 1.1

model:
    script:
        source: unet2d.py
        hash: 12
    weights:
        source: link/to/weights.torch
        hash: 42
    class_name: UNet2D
    kwargs: {input_channels: 1, output_channels: 1}
    documentation: unet2d.md
    input_axes: "cyx"
    input_size: [1, 256, 256]
    minimal_valid_step: [0, 32, 32]
    output_axes: "cyx"

training:
    loss:
        name: BCELoss
        kwargs: {reduction: "mean"}
        transformations:
            - Sigmoid
    optimizer:
        name: Adam
        kwargs: {beta: 0.01}
    pretrained_on:
        - {source: doi1, hash: 21}
    batch_size: 4

data:
    input_transformations:
        - Normalize
    output_transformations:
        - Sigmoid

meta:
    description: A 2d U-Net pretrained on ISBI2012 EM segmentation challenge.
    cite: Ronneberger et al.
    parent_model: 2d-unet
