version: 0.0.1
language: python
framework:
    pytorch: 1.1

model:
    definition: link/to/definition.py
    weights:
        source: link/to/weights.torch
        hash: 42
    documentation: link/to/doc.md

training:
    loss: BinaryCrossEntropy
    optimizer:
        Adam:
            beta: 0.01
    pretrained_on:
        source: doi
        hash: 21
    batch_size: 4
    target:
        task: "Segmentation"
        n_classes: 2

data:
    input_axes: "cyx"
    input_channels: 1
    input_transformations:
        - Normalize
    output_axes: "cyx"
    output_channels: 1
    patch_size: [256, 256]
    valid_step: [32, 32]

info:
    name: UNet2D
    description: A 2d U-Net pretrained on ISBI2012 EM segmentation challenge.
    cite: Ronneberger et al.
    parent_model: 2d-unet
